version: "3.8"

services:
  # LocalTunnel Server (already running)
  localtunnel-server:
    image: localtunnel-server
    container_name: localtunnel-server
    ports:
      - "3000:80"
    networks:
      - tunnel-network
    restart: unless-stopped

  # Customer Dashboard
  customer-dashboard:
    build:
      context: ./client_app
      dockerfile: Dockerfile
      args:
        - VITE_TUNNEL_SERVER_URL=http://localtunnel-server:80
        - VITE_DEFAULT_SERVER_HOST=YOUR_IP_ADDRESS
    container_name: customer-dashboard
    ports:
      - "8080:80"
    networks:
      - tunnel-network
    depends_on:
      - localtunnel-server
    restart: unless-stopped

networks:
  tunnel-network:
    driver: bridge
